# Generated by Django 4.0.5 on 2022-11-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('PassWord', models.CharField(max_length=16, verbose_name='密码')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户token')),
            ],
        ),
    ]
